### ISSUE TITLE
Travis Builds do not work properly

### ISSUE THREAD

**Issue by logokas** [logokas/ddcc#37]
For whatever reason, Travis does not build an RPA file that ren'py would prioritize to load new script files from, and defaults to using old ones, resulting in broken game when loaded.

Repro: try any Travis build built on, or before, May 25, 2019.

> [code]
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/ddcc.rpy", line 1, in script
>   File "game/ddcc.rpy", line 2, in <module>
> NameError: name 'Skit' is not defined
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/ddcc.rpy", line 1, in script
>   File "D:\Games\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "D:\Games\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/ddcc.rpy", line 2, in <module>
> NameError: name 'Skit' is not defined
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
>  
> [/code]

**Comment by logokas** [comment]
Current workaround is to have the build replace scripts.rpa entirely. This may be a permanent solution to the problem, as it would be too troublesome to resolve in a more non-destructive way.

**Comment by Bronya-Rand** [comment]
Part of PR #38 .

**Comment by logokas** [comment]
This is now resolved.
